@server = http://localhost:4004
@alice = Authorization: Basic alice

GET {{server}}/odata/v4/travel/Travels?$filter=ID eq 4133
{{alice}}
###

GET {{server}}/odata/v4/travel/Travels(ID=4133)
{{alice}}
###

GET {{server}}/odata/v4/travel/Travels/4133/true
{{alice}}
###

GET {{server}}/odata/v4/travel/Travels(ID=4133,IsActiveEntity=true)
{{alice}}
###
