@server = http://localhost:4004
@alice = Authorization: Basic alice

GET {{server}}/processor/Travel?$filter=ID eq 4133
{{alice}}
###

GET {{server}}/processor/Travel(TravelUUID='73757221A8E4645C17002DF03754AB66')
{{alice}}
###

GET {{server}}/processor/Travel/73757221A8E4645C17002DF03754AB66/true
{{alice}}
###

GET {{server}}/processor/Travel(TravelUUID='73757221A8E4645C17002DF03754AB66',IsActiveEntity=true)
{{alice}}
###

GET {{server}}/odata/v4/travel/Travels?$compute=(BookingFee mul 100) divby TotalPrice as PctOfAdminCosts&$select=PctOfAdminCosts,TotalPrice,BookingFee
{{alice}}