features:
  ieee754compatible: true # REVISIT: Why do we need that ??
"[fed-srv]":
  features:
    with_mocks: false
  requires:
    sap.capire.flights.data:
      kind: odata
      model: "@capire/xflights"
      credentials:
        url: http://localhost:4005/odata/v4/data/
"[fed-vrt]":
  features:
    with_mocks: false
  requires:
    db: hana
    sap.capire.flights.data:
      kind: odata
      credentials:
        remote: xflights
        schema: XFLIGHTS_XFLIGHTS
        supportRealTimeCDC: true
"[fed-syn]":
  features:
    with_mocks: false
  requires:
    db: hana
    sap.capire.flights.data:
      kind: odata
      vcap: xflights
      credentials:
        schema: XFLIGHTS_XFLIGHTS
"[fed-ds]":
  features:
    with_mocks: false
  requires:
    db: hana
    sap.capire.flights.data:
      kind: odata
      vcap:
        name: xflights-datasphere
      credentials:
        sql:
          names: quoted
"[fed-rap]":
  features:
    with_mocks: false
  requires:
    db: hana
    rap_v2:
      kind: odata
      model: db/abap
      credentials:
        remote: sflight-rap
        sql:
          names: quoted
        service: false
        supportRealTimeCDC: false
